version: '2'
services:
    jwebshop-app:
        image: jwebshop
        external_links:
            - jwebshop-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/JWebShop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jwebshop-postgresql:
        extends:
            file: postgresql.yml
            service: jwebshop-postgresql
